name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for creating the first issue. <br> **Welcome to open source community.**'
        pr-message: 'Thanks for creating the first push request. <br> **Welcome to open source community.**'
